Introducing SuspensionInfo and suspension chain parameters
Concordium/concordium-node pull request #1264
Opened 2024-12-02 14:46 UTC by drsk0

## Purpose

These are the corresponding changes for the newly introduced validator suspension chain parameters in the node repo. Also a data structure `SuspensionInfo` is introduced that gathers the missed rounds and whether a validator is primed for suspension at the next snapshot.

## Changes

See above

## Checklist

- [x] My code follows the style of this project.
- [x] The code compiles without warnings.
- [x] I have performed a self-review of the changes.
- [x] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [x] (If necessary) I have updated the CHANGELOG.

## CLA acceptance

_Remove if not applicable.

By submitting the contribution I accept the terms and conditions of the
Contributor License Agreement v1.0
- link: https://developers.concordium.com/CLAs/Contributor-License-Agreement-v1.0.pdf

- [x] I accept the above linked CLA.

2024-12-03 10:51 UTC, td202 reviewed
Base submodule requires updating.

2024-12-04 15:33 UTC, td202 requested changes

2024-12-04 15:33 UTC, td202 commented on concordium-consensus/src/Concordium/GlobalState/Persistent/BlockState/Updates.hs
It looks like updating the new parameter is missing from `processUpdateQueues`. Please double check that everything that is done for the other queues is also done for the new one.

2024-12-04 15:33 UTC, td202 commented on concordium-consensus/src/Concordium/GlobalState/PoolRewards.hs
> +      -- | Information for deciding whether a validator will be suspended the next snapshot epoch.
```suggestion
      -- | Information for deciding whether a validator will be suspended at the next snapshot epoch.
```

2024-12-04 18:09 UTC, drsk0 commented on concordium-consensus/src/Concordium/GlobalState/Persistent/BlockState/Updates.hs
I did another grep `FinalizationCommitteeParameters`, it seems all the boilerplate should be there now. However, I forgot to add the new chain parameter version in the grpc api: https://github.com/Concordium/concordium-grpc-api/pull/73.

2024-12-05 09:58 UTC, td202 approved these changes
Looks good!

2024-12-05 14:44 UTC, merged