Extend ValidatorAdd with a suspended field
Concordium/concordium-node pull request #1302
Opened 2024-12-16 15:30 UTC by drsk0

## Purpose

Closes #1246 . Validators can now be added already suspended.

## Changes

Extends the `ValidatorAdd` field with a new `vaSuspended` field.

## Checklist

- [ ] My code follows the style of this project.
- [ ] The code compiles without warnings.
- [ ] I have performed a self-review of the changes.
- [ ] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [ ] (If necessary) I have updated the CHANGELOG.

## CLA acceptance

_Remove if not applicable.

By submitting the contribution I accept the terms and conditions of the
Contributor License Agreement v1.0
- link: https://developers.concordium.com/CLAs/Contributor-License-Agreement-v1.0.pdf

- [ ] I accept the above linked CLA.

2025-01-07 09:27 UTC, td202 requested changes
It would also be nice to have test coverage for this.

2025-01-07 09:27 UTC, td202 commented on concordium-consensus/src/Concordium/GlobalState/BakerInfo.hs
> +      vaSuspended :: !Bool
`newAddValidator` needs to be updated to actually set `_bieIsSuspended`.

2025-01-07 11:19 UTC, drsk0 commented on concordium-consensus/src/Concordium/GlobalState/BakerInfo.hs
> +      vaSuspended :: !Bool
this has been updated.

2025-01-07 11:19 UTC, drsk0 commented
working on the tests

2025-01-07 14:33 UTC, drsk0 commented on concordium-consensus/tests/globalstate/GlobalStateTests/ConfigureValidator.hs
> +      vcSuspended :: Bool
It's not really a failure condition, but fits well here.

2025-01-08 12:24 UTC, drsk0 commented on concordium-consensus/tests/globalstate/GlobalStateTests/ConfigureValidator.hs
> +      vcSuspended :: Bool
I'm changing this.

2025-01-08 13:26 UTC, eb-concordium approved these changes

2025-01-08 13:40 UTC, td202 approved these changes
Looks good! Thanks.

2025-01-09 14:36 UTC, td202 commented on concordium-consensus/src/Concordium/GlobalState/Persistent/BlockState.hs
> +--
This should also be reflected in the docs on `bsoUpdateValidator`.

2025-01-09 14:45 UTC, drsk0 commented on concordium-consensus/src/Concordium/GlobalState/Persistent/BlockState.hs
> +--
done.

2025-01-09 15:31 UTC, merged