WIP: Transaction memos
Concordium/concordium-node pull request #141
Opened 2021-08-25 14:37 UTC by eb-concordium

## Purpose

To add user-defined metadata to inter-account transfers. This will enable senders to attach free-form data to transfers that will enable them to convey additional information to the receiver. 

Closes parts of https://github.com/Concordium/concordium-node/issues/115 and 

## Changes

The following changes have been done:
- The scheduler can now handle the new transaction types.
- A memo protocol update has been introduced.

## Checklist

- [ ] My code follows the style of this project.
- [ ] The code compiles without warnings.
- [ ] I have performed a self-review of the changes.
- [ ] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [ ] (If necessary) I have updated the CHANGELOG.

2021-08-31 14:44 UTC, td202 requested changes
A few small things, but otherwise looks good.

2021-08-31 14:44 UTC, td202 commented on concordium-consensus/src/Concordium/ProtocolUpdate/P1.hs
> +import qualified Concordium.ProtocolUpdate.P1.Memo as Memo
Since the `Memo` constructor has been renamed to `ProtocolP2`, I think the module should also be renamed to match.

2021-09-01 06:41 UTC, abizjak approved these changes

2021-09-01 08:43 UTC, td202 commented on concordium-consensus/src/Concordium/ProtocolUpdate/P1/ProtocolP2.hs
> +-- This produces a new 'GenesisDataP2' using the 'GenesisDataP2' constructor,
```suggestion
-- This produces a new 'GenesisDataP2' using the 'GDP2Regenesis' constructor,
```

2021-09-01 10:53 UTC, abizjak approved these changes

2021-09-01 11:03 UTC, td202 approved these changes
One minor comment, otherwise good to go.

2021-09-01 11:03 UTC, td202 commented on concordium-consensus/src/Concordium/Scheduler.hs
> +                            ] ++ (TransferMemo <$> maybeToList maybeMemo)
Suggest using `:` rather than `++`.

2021-09-01 11:10 UTC, merged