Update concordium-base
Concordium/concordium-node pull request #592
Opened 2022-11-08 08:57 UTC by limemloh

## Purpose

Update concordium-base to the one which uses `bs58` 
Should be merged after https://github.com/Concordium/concordium-contracts-common/pull/51 and https://github.com/Concordium/concordium-base/pull/259

2022-11-08 13:40 UTC, abizjak requested changes

2022-11-08 13:40 UTC, abizjak commented on concordium-node/Cargo.lock
>   "hashbrown 0.11.2",
base58check is still listed as a dependency of concordium-node. Please resolve that as well.

2022-11-09 04:41 UTC, abizjak approved these changes

2022-11-09 10:01 UTC, Bargsteen approved these changes

2022-11-10 11:52 UTC, merged