Migrate account schedules without using basic
Concordium/concordium-node pull request #625
Opened 2022-11-29 09:01 UTC by limemloh

## Purpose

Migrate account release schedule during the P4 to P5 upgrade without using the pure representation defined in Basic block state.
Closes #616.

## Checklist

- [x] My code follows the style of this project.
- [x] The code compiles without warnings.
- [x] I have performed a self-review of the changes.
- [x] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [x] (If necessary) I have updated the CHANGELOG.

2022-11-29 16:21 UTC, td202 requested changes

2022-11-29 16:21 UTC, td202 commented on concordium-consensus/src/Concordium/GlobalState/Persistent/BlockState/AccountReleaseScheduleV1.hs
> +import Concordium.Utils.Serialization
Can we keep the imports in three blocks: external libraries, base, consensus.

2022-12-01 07:43 UTC, limemloh commented on concordium-consensus/src/Concordium/GlobalState/Persistent/BlockState/AccountReleaseScheduleV1.hs
> +                releases <- refLoad release >>= ARSV0.listRelease
Good catch, this is very subtle

2022-12-01 09:30 UTC, abizjak approved these changes

2022-12-01 09:30 UTC, abizjak commented on concordium-consensus/src/Concordium/GlobalState/Persistent/BlockState/AccountReleaseSchedule.hs
> +-- The list will always be non-empty.
```suggestion
-- The list will never be empty.
```

2022-12-04 13:30 UTC, merged