Enable out-of-band catch-up on Windows by default
Concordium/concordium-node pull request #963
Opened 2023-07-12 13:36 UTC by td202

## Purpose

Update the node configuration set up by the Windows installer to enable out-of-band catch-up by default.

## Changes

- Set the `CONCORDIUM_NODE_CONSENSUS_DOWNLOAD_BLOCKS_FROM` environment variable for the node for mainnet and testnet configurations.

## Checklist

- [ ] My code follows the style of this project.
- [ ] The code compiles without warnings.
- [ ] I have performed a self-review of the changes.
- [ ] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [ ] (If necessary) I have updated the CHANGELOG.

2023-07-12 13:42 UTC, abizjak requested changes
I don't want to add this to the 6.0 release. We should add this to all or none of the distributions, and then we need to make sure we don't have problems with it during testing.

It can go into the following release in October, where also we can make sure that there are no issues on any of t he distributions.

2023-07-13 06:43 UTC, limemloh approved these changes

2023-07-13 06:56 UTC, abizjak commented
@td202 Please make a task for this for the next 6.1 release to cover
- updating all distributions
- making sure we update all our documentation to reflect the new defaults

2023-09-12 09:29 UTC, abizjak approved these changes
Rasmus will do other distributions and update the documentation. This can be merged now.

2023-09-29 06:32 UTC, merged